# Copy this file to application-local.yml and set your specific local test settings (e.g. Shopify Test Store Name, Shopify API key and secret, and token encryption key)
debug: true

spring:
  mvc:
    log-request-details: true
  application:
    admin:
      enabled: true

logging:
  level:
    org.springframework.web: DEBUG
    org.springframework.web.filter.CommonsRequestLoggingFilter: TRACE
    org.springframework.security: TRACE
    com.justblackmagic: TRACE
#    reactor.netty.http.client: TRACE
    
server:
  servlet:
    session:
      cookie.secure: false
      persistent: false

shopify:
  app:
    hostname: $YOUR-APP-HOSTNAME
    embedded: true
  auth:
    apiKey: $YOUR-api-key
    apiSecret: $YOUR-api-secret
    tokenEncryptionKey: $YOUR-token-encryption-key - can generate here - https://www.digitalsanctuary.com/aes-key-generator-free
  test:
    storeName: $YOUR-TEST-STORE.myshopify.com
  security:
    unprotectedURIs: /,/index.html,/favicon.ico,/error,/css/*,/js/*,/dist/*,/img/*,/dash-embedded,/embedded-auth-check,/product-list
    authSeccessPage: /dash-embedded

